name: Continuous Integration
on:
    push:
        branches: [rebuild]
jobs:
    integrate-client:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./client
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - run: npm ci
            - run: npm run build
            - run: npm test
            - run: npm e2e
